apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager1
resources:
  - issuer.yaml 
  - release.yaml
  - namespace.yaml
configMapGenerator:
  - name: values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml