apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 24h0m0s
  install:
    createNamespace: true
    remediation:
      retries: 4
  valuesFrom:
    - kind: ConfigMap
      name: values