apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: buttons
resources:
  - namespace.yaml
  - release.yaml
  - postgres.yaml
configMapGenerator:
  - name: values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml