apiVersion: v1
kind: Secret
metadata:
  name: your-regcred
  namespace: buttons
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "kimbiharbor.hackster.me": {
          "username": "admin",
          "password": "7HwP2bw9HSf9jmLaaJVsO4"
        }
      }
    }