apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: buttons
  namespace: buttons
spec:
  releaseName: buttons
  chart:
    spec:
      chart: buttons
      sourceRef:
        kind: HelmRepository
        name: buttons
        namespace: flux-system
      version: "*"
  interval: 0h1m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: values