apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: buttons
  labels:
    app: nginx
    app.kubernetes.io/name: buttons
spec:
  selector:
    app: nginx
    app.kubernetes.io/name: buttons
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: python
  namespace: buttons
  labels:
    app: python
    app.kubernetes.io/name: buttons
spec:
  selector:
    app: python
    app.kubernetes.io/name: buttons
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP