imagePullSecrets:
  - name: your-regcred

nginx:
  image:
    repository: kimbiharbor.hackster.me/application/nginx
    tag: "main-c2d24b8-1740567239"
  name: nginx



ingress:
  enabled: true
  className: "nginx"
  annotations: 
     nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
     cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: kimbi.hackster.me
      paths:
        - path: /
          pathType: ImplementationSpecific
          service:
            name: "nginx"
            port: 80
  tls: 
   - secretName: chart-example-tls
     hosts:
       - kimbi.hackster.me

---
apiVersion: v1
kind: Secret
metadata:
  name: your-regcred
  namespace: buttons
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "kimbiharbor.hackster.me": {
          "username": "admin",
          "password": "7HwP2bw9HSf9jmLaaJVsO4"
        }
      }
    }