apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: nginx
  namespace: buttons
spec:
  image: kimbiharbor.hackster.me/application/nginx
  interval: 1m
  secretRef:
    name: your-regcred

