apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
resources:
  - namespace.yaml
  # - release.yaml
configMapGenerator:
  - name: values
    namespace: harbor
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml