apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 1h
  chart:
    spec:
      chart: harbor
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  # valuesFrom:
  #   - kind: ConfigMap
  #     name: values
  values:
    expose:
      type: ingress
      tls:
        enabled: true
      ingress:
        hosts:
          core: kimbiharbor.hackster.me
          notary: notary.kimbiharbor.hackster.me
        controller: default
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          ingress.kubernetes.io/ssl-redirect: "true"
    
    externalURL: https://kimbiharbor.hackster.me