externalURL: https://kimbiharbor.hackster.me
exposureType: ingress
ingress:
  hosts:
    core: kimbiharbor.hackster.me
  controller: default
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    enabled: true