expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
  ingress:
    hosts:
      core: kimbiharbor.hackster.me
      notary: notary.kimbiharbor.hackster.me
    controller: default
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      ingress.kubernetes.io/ssl-redirect: "true"

externalURL: https://kimbiharbor.hackster.me

database:
  type: internal

harborAdminPassword: "Harbor12345"

persistence:
  enabled: true